### PR TITLE
Upgrade to Sequelize v5

### LINKED ISSUE #40: Cannot read property 'reduce' of undefined
Hi, i am facing the following issue.
Unhandled rejection TypeError: Cannot read property 'reduce' of undefined
    at MySQL.end (E:\xampp\htdocs\echallan\node_modules\@aclify\aclify\dist\src\stores\sequelize.js:48:28)

### PR DESCRIPTION
**Pull request by marklawlor**
Fixes #40, #36 

For reference: http://docs.sequelizejs.com/manual/upgrade-to-v5.html

### CODE REVIEW

**Comment by marklawlor** [comment]
Issue #36 still remains, due to the `{where: {key: {$in: [] } }` queries.

A quick fix is to provide an `operatorsAliases` option on your Sequelize instance. You will get a deprecation notice (string operators where deprecated in v4) but it will work.

**Comment by rimiti** [comment]
@Nadeem1337 could you please test this fix? (I'm currently busy to test it)

@marklawlor Thank you for your contribution! 🙏

**Comment by marklawlor** [comment]
Upgraded the version of Sequelize to v5 and removed the deprecated operators.

This should still be backwards compatible with anyone using Sequelize v4

**Review by rimiti — APPROVED** [review]
@marklawlor It's an amazing work, thank you! 🙏 🚀 

I'll release today. 👍

**Pull request merged**
